---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      username: ((DOCKER_HUB_USERNAME))
      password: ((DOCKER_HUB_PASSWORD))
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
      username: ((DOCKER_HUB_USERNAME))
      password: ((DOCKER_HUB_PASSWORD))
  - name: github-webhook-resource
    type: docker-image
    source:
      repository: homedepottech/github-webhook-resource
      tag: latest
      username: ((DOCKER_HUB_USERNAME))
      password: ((DOCKER_HUB_PASSWORD))

resources:
  - name: git-ci-sdk-js
    type: git
    source:
      uri: git@github.com:teamleadercrm/sdk-js.git
      branch: master
      private_key: ((TEAMLEADER_PRIVATE_KEY))
      paths: [ci]
    icon: github
  - name: git-ci-pull-request
    type: pull-request
    webhook_token: ((TEAMLEADER_WEBHOOK_TOKEN))
    source:
      access_token: ((GITHUB_ACCESS_TOKEN))
      repository: teamleadercrm/sdk-js
      paths: ['ci/*']
    icon: github
  - name: git-pull-request
    type: pull-request
    webhook_token: ((TEAMLEADER_WEBHOOK_TOKEN))
    source:
      access_token: ((GITHUB_ACCESS_TOKEN))
      repository: teamleadercrm/sdk-js
    icon: github

  # Docker image
  - name: docker-node
    type: docker-image
    check_every: 24h
    source:
      repository: node
      tag: '16-slim'
    icon: docker
  - name: docker-fly-validate
    type: docker-image
    check_every: 24h
    source:
      repository: teamleader/concourse-fly
      tag: ((DOCKER_FLY_VALIDATE_TAG))
      username: ((DOCKER_HUB_USERNAME))
      password: ((DOCKER_HUB_PASSWORD))
  - name: docker-yamllint
    type: docker-image
    check_every: 24h
    source:
      repository: teamleader/yamllint
      tag: latest
      username: ((DOCKER_HUB_USERNAME))
      password: ((DOCKER_HUB_PASSWORD))

  - name: slack-alert
    type: slack-notification
    check_every: 24h
    source:
      # slack channel: dev-ci
      url: https://hooks.slack.com/services/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
    icon: slack

  - name: github-webhook
    type: github-webhook-resource
    check_every: 24h
    source:
      github_api: https://api.github.com
      github_token: ((GITHUB_ACCESS_TOKEN))

groups:
  - name: sdk-js
    jobs:
      - pr-linting
      - pr-testing
      - pr-check-types
  - name: sdk-js-ops
    jobs:
      - pr-yamllint
      - pr-fly-validate
      - yamllint
      - fly-validate
      - set-pipeline
      - create-repository-ci-webhook

jobs:
  - name: pr-linting
    plan:
      - in_parallel:
          - get: git-pull-request
            trigger: true
            version: every
          - get: docker-node
            params: {save: true}
      - put: git-pull-request
        params:
          path: git-pull-request
          status: pending
          context: linting
      - task: linting
        image: docker-node
        config:
          platform: linux
          caches:
            - path: git-pull-request/node_modules
          inputs:
            - name: git-pull-request
          run:
            path: sh
            args:
              - -exec
              - |
                cd git-pull-request
                yarn
                yarn lint
    on_success:
      put: git-pull-request
      params:
        path: git-pull-request
        status: success
        context: linting
    on_failure:
      put: git-pull-request
      params:
        path: git-pull-request
        status: failure
        context: linting

  - name: pr-testing
    plan:
      - in_parallel:
          - get: git-pull-request
            trigger: true
            version: every
          - get: docker-node
            params: {save: true}
      - put: git-pull-request
        params:
          path: git-pull-request
          status: pending
          context: testing
      - task: testing
        image: docker-node
        config:
          platform: linux
          caches:
            - path: git-pull-request/node_modules
          inputs:
            - name: git-pull-request
          run:
            path: sh
            args:
              - -exec
              - |
                cd git-pull-request
                yarn
                yarn test
    on_success:
      put: git-pull-request
      params:
        path: git-pull-request
        status: success
        context: testing
    on_failure:
      put: git-pull-request
      params:
        path: git-pull-request
        status: failure
        context: testing

  - name: pr-check-types
    plan:
      - in_parallel:
          - get: git-pull-request
            trigger: true
            version: every
          - get: docker-node
            params: {save: true}
      - put: git-pull-request
        params:
          path: git-pull-request
          status: pending
          context: check-types
      - task: check-types
        image: docker-node
        config:
          platform: linux
          caches:
            - path: git-pull-request/node_modules
          inputs:
            - name: git-pull-request
          run:
            path: sh
            args:
              - -exec
              - |
                cd git-pull-request
                yarn
                yarn check-types
    on_success:
      put: git-pull-request
      params:
        path: git-pull-request
        status: success
        context: check-types
    on_failure:
      put: git-pull-request
      params:
        path: git-pull-request
        status: failure
        context: check-types

  # OPS jobs

  - name: pr-yamllint
    plan:
      - in_parallel:
          - get: git-ci-pull-request
            trigger: true
            version: every
          - get: docker-yamllint
            params: {save: true}
      - put: git-ci-pull-request
        params:
          path: git-ci-pull-request
          status: pending
          context: yamllint
      - task: yamllint
        image: docker-yamllint
        file: git-ci-pull-request/ci/yamllint.yaml
        input_mapping:
          git-ci-sdk-js: git-ci-pull-request
    on_success:
      put: git-ci-pull-request
      params:
        path: git-ci-pull-request
        status: success
        context: yamllint
    on_failure:
      put: git-ci-pull-request
      params:
        path: git-ci-pull-request
        status: failure
        context: yamllint

  - name: pr-fly-validate
    plan:
      - in_parallel:
          - get: git-ci-pull-request
            trigger: true
            version: every
          - get: docker-fly-validate
            params: {save: true}
      - put: git-ci-pull-request
        params:
          path: git-ci-pull-request
          status: pending
          context: fly-validate
      - task: fly-validate
        image: docker-fly-validate
        file: git-ci-pull-request/ci/fly-validate.yaml
        input_mapping:
          git-ci-sdk-js: git-ci-pull-request
    on_success:
      put: git-ci-pull-request
      params:
        path: git-ci-pull-request
        status: success
        context: fly-validate
    on_failure:
      put: git-ci-pull-request
      params:
        path: git-ci-pull-request
        status: failure
        context: fly-validate

  - name: fly-validate
    plan:
      - in_parallel:
          - get: docker-fly-validate
            params: {save: true}
          - get: git-ci-sdk-js
            trigger: true
      - task: fly-validate
        image: docker-fly-validate
        file: git-ci-sdk-js/ci/fly-validate.yaml

  - name: yamllint
    plan:
      - in_parallel:
          - get: docker-yamllint
            params: {save: true}
          - get: git-ci-sdk-js
            trigger: true
      - task: yamllint
        image: docker-yamllint
        file: git-ci-sdk-js/ci/yamllint.yaml

  - name: set-pipeline
    plan:
      - get: git-ci-sdk-js
        trigger: true
        passed: [fly-validate, yamllint]
      - set_pipeline: sdk-js
        file: git-ci-sdk-js/ci/pipeline.yaml
        var_files:
          - git-ci-sdk-js/ci/common-vars.yaml
    on_failure: ((SLACK_ON_FAILURE))

  - name: create-repository-ci-webhook
    plan:
      - in_parallel:
          - put: create-pr-webhook
            resource: github-webhook
            params:
              org: teamleadercrm
              repo: sdk-js
              resource_name: git-pull-request
              webhook_token: ((TEAMLEADER_WEBHOOK_TOKEN))
              operation: create
              events: [push, pull_request]
          - put: create-ci-pr-webhook
            resource: github-webhook
            params:
              org: teamleadercrm
              repo: sdk-js
              resource_name: git-ci-pull-request
              webhook_token: ((TEAMLEADER_WEBHOOK_TOKEN))
              operation: create
              events: [push, pull_request]
